### ISSUE TITLE
[BUG] unable to find version `latest`

### ISSUE THREAD

**Issue by george-gca** [AbdulRehman-1/pr-prettier#1]
**What exactly happened?**

1. Create a Github action pointing to `latest` version, like this:

```yml
name: Prettier

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  format:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      - name: Run Prettier
        uses: AbdulRehman-1/pr-prettier@latest
        with:
          only_changed: true
          prettier_options: --write **/*.{css,html,js,json,md,sass,scss,yaml,yml}
```

**What should've happened?**

Action runned successfully

**Where did you encounter the problem?**

Running in my own repo.

- Pretier workflow: https://github.com/george-gca/diciotech/blob/3d577c685349bcefa7c1529b9813ee72a17d5438/.github/workflows/prettier.yml
- Failed action: https://github.com/levxyca/diciotech/actions/runs/11467021100/job/31908999795?pr=240
- Version: latest

Maybe `latest` tag is not linked? When I click on the marketplace it suggests using `initial`

![image](https://github.com/user-attachments/assets/ca2360fa-9d98-4f04-8840-24acc004d428)
