### ISSUE TITLE
[BUG] Error: A branch or tag with the name 'prettier' could not be found

### ISSUE THREAD

**Issue by george-gca** [AbdulRehman-1/pr-prettier#2]
**What exactly happened?**

1. Create a workflow like this:

```yml
name: Prettier

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  format:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      - name: Run Prettier
        uses: AbdulRehman-1/pr-prettier@initial
        with:
          only_changed: true
          prettier_options: --write **/*.{css,html,js,json,md,sass,scss,yaml,yml}
```

**What should've happened?**

Run workflow successfully

**Where did you encounter the problem?**

My repo

- Workflow file: https://github.com/george-gca/diciotech/blob/7fd0f26ceb37da82bc113054cb2d9048f8932dff/.github/workflows/prettier.yml
- Failed action: https://github.com/levxyca/diciotech/actions/runs/11467142909/job/31909374800?pr=240
- Version: `initial`

Full stacktrace:

```
Determining the checkout info
  /usr/bin/git branch --list --remote origin/prettier
  /usr/bin/git tag --list prettier
  Error: A branch or tag with the name 'prettier' could not be found
```

Just by removing 

```yml
        with:
          ref: ${{ github.head_ref }}
```

from the `checkout` action seems to have solved.
